version: '3.1'
services:
  ghost:
    image: 'ghost:4-alpine'
    ports:
      - '8080:2368'
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      url: 'http://localhost:8080'
    volumes:
      - './themes:/var/lib/ghost/content/themes'
  db:
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: example